# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with:
        path: randomiser
        
    - name: Check mod launcher version
      id: mod-launcher-version
      run: |
        $Request = Invoke-WebRequest -Uri "https://api.donutteam.com/?Event=AppLookup&Apps=4&Format=XML" -Method:Get -ErrorAction:Stop -TimeoutSec 60
        $Version = ([XML]$Request.Content).DonutTeamAPI.Data.Version
        Write-Output "::set-output name=version::$Version"

    # Runs a single command using the runners shell
    - name: Cache mod launcher
      id: cache-mod-launcher
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-shar-mod-launcher-${{ steps.mod-launcher-version.outputs.version }}
        path: './mod-launcher'
      
    - name: Download mod launcher
      if: steps.cache-mod-launcher.outputs.cache-hit != 'true'
      uses: carlosperate/download-file-action@v1.0.3
      id: download-mod-launcher
      with:
        file-url: "https://cdn.donutteam.com/Downloads/Tools/Lucas'%20Simpsons%20Hit%20&%20Run%20Mod%20Launcher%20${{ steps.mod-launcher-version.outputs.version }}.zip"
        file-name: 'launcher.zip'
        location: './'
      
    - name: Extract mod launcher
      if: steps.cache-mod-launcher.outputs.cache-hit != 'true'
      run: |
        Expand-Archive -LiteralPath '.\launcher.zip' -DestinationPath '.\mod-launcher'
        
    - name: Compile mod
      run: |
        & '.\mod-launcher\Lucas Simpsons Hit & Run Mod Launcher.exe' -ignoreloaderrors -mods ".\randomiser" -compile "Randomiser" -outputpath ".\" | Out-String
        
    - name: Upload mod
      uses: actions/upload-artifact@v4
      with:
        name: Randomiser mod
        path: Randomiser.lmlm
      
    - name: Upload frameworks
      uses: actions/upload-artifact@v4
      with:
        name: Additional frameworks
        path: |
          randomiser/RandomiserCars
          randomiser/RandomiserChars
          randomiser/RandomiserDialogue
          
  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./
      - name: Create archive
        run: |
          mv  "./Randomiser mod/Randomiser.lmlm" .
          zip -r Randomiser.zip "./Randomiser.lmlm" "./Additional frameworks"
      - uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./Randomiser.zip
          tag: auto-build-${{ github.ref }}
